name: ZMF CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  verify-generated-code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.25'
    - name: Install protoc v6.32.0
      run: |
        curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v32.0/protoc-32.0-linux-x86_64.zip
        sudo unzip -o protoc-32.0-linux-x86_64.zip -d /usr/local bin/protoc
        sudo unzip -o protoc-32.0-linux-x86_64.zip -d /usr/local 'include/*'
        rm protoc-23.4-linux-x86_64.zip

    - name: Install Go dependencies
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.8
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2

    - name: Generate protobuf code
      run: make generate

    - name: Verify generated code is up-to-date
      run: |
        echo "--- Diff after make generate in CI (should be empty for success) ---"
        git diff zerfoo.pb.go
        echo "--- End of post-generate diagnostics ---"
        if ! git diff --exit-code; then
          echo "Generated code is not up-to-date. Please run 'make generate' and commit the changes."
          exit 1
        fi

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - name: Run linter
        uses: golangci/golangci-lint-action@v8

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - name: Run tests
        run: go test ./...
